name: "Generalized Terraform Plan Workflow"
description: "A reusable action for running Terraform plan in any environment"

inputs:
  app-id:
    description: "GitHub App ID"
    required: true
  aws-region:
    description: "AWS region to use"
    required: true
  aws-role:
    description: "The AWS role to assume for the environment"
    required: true
  environment:
    description: "The environment to use (e.g., dev, prod)"
    required: true
  private-key:
    description: "GitHub App Private Key"
    required: true
  python-version:
    description: "Python version to use"
    required: false
    default: "3.12"
  terraform-version:
    description: "Terraform version to use"
    required: false
    default: "1.8.4"
  working-dir:
    description: "The working directory for Terraform files"
    required: true

runs:
  using: "composite"
  steps:
    - name: Create GitHub App Token
      uses: actions/create-github-app-token@v1
      id: github-app-token
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}

    - name: Checkout source
      uses: actions/checkout@v4
      with:
        token: ${{ steps.github-app-token.outputs.token }}
        ref: ${{ github.head_ref }}
        persist-credentials: false

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: Config Terraform plugin cache
      run: |
        echo 'plugin_cache_dir="$HOME/.terraform.d/plugin-cache"' >~/.terraformrc
        mkdir --parents ~/.terraform.d/plugin-cache

    - name: Cache Terraform
      uses: actions/cache@v4
      with:
        path: |
          ~/.terraform.d/plugin-cache
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
        restore-keys: |
          ${{ runner.os }}-terraform-

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install pipx
      run: |
        python -m pip install --user pipx
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install git-secret-protector
      run: |
        pipx install git-secret-protector

    - name: Configure AWS Credentials for ${{ inputs.environment | toUpperCase }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role }}
        role-session-name: gh-actions
        aws-region: ${{ inputs.aws-region }}

    - name: Pull AES key and IV for ${{ inputs.environment | toUpperCase }}
      run: |
        git-secret-protector pull-aes-key app-${{ inputs.environment }}

    - name: Decrypt ${{ inputs.environment | toUpperCase }} secrets
      run: |
        git-secret-protector decrypt-files app-${{ inputs.environment }}

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check -diff
      working-directory: ${{ inputs.working-dir }}

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ${{ inputs.working-dir }}

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: ${{ inputs.working-dir }}

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -input=false -no-color -lock=false -refresh=false -out=/tmp/plan.tmp
        terraform show -no-color /tmp/plan.tmp > /tmp/plan.out
        rm -f /tmp/plan.tmp
      continue-on-error: true
      working-directory: ${{ inputs.working-dir }}

    - name: Clean git-secret-protector stage files for ${{ inputs.environment | toUpperCase }}
      run: |
        git-secret-protector encrypt-files app-${{ inputs.environment }}
        rm -rf .git_secret_protector

    - name: Check for Plan Failure
      if: steps.plan.outputs.exitcode == 1
      run: |
        echo "::error:: Terraform plan failed"
        exit 1

    - uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ steps.github-app-token.outputs.token }}
        script: |
          const fs = require('fs')
          const plan = fs.readFileSync('/tmp/plan.out', 'utf8')
          fs.unlinkSync('/tmp/plan.out')
          const output = `#### Environment: ${{ inputs.environment | toUpperCase }}
          #### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
          <details><summary>Validation Output</summary>

          \`\`\`\n
          ${{ steps.validate.outputs.stdout }}
          \`\`\`

          </details>

          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

          <details><summary>Show Plan</summary>

          \`\`\`\n
          ${plan}
          \`\`\`

          </details>

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ inputs.working-dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
