name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.*

defaults:
  run:
    shell: bash

jobs:
  create-release:
    if: github.repository_owner == 'c0x12c'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: github-app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          title: $version
          branch: 'master|v[0-9]+'
          token: ${{ steps.github-app-token.outputs.token }}
